services:
  db:
    image: mariadb:latest
    container_name: 'unideal-db'
    environment:
      # MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: unideal
      MYSQL_USER: unideal
      MYSQL_PASSWORD: changeme
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - unideal-db_data:/var/lib/mysql
  app:
    image: ghcr.io/modernweb-team3/backend:main
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 10001:8080
    # Refer to this for environment setup:
    # https://docs.spring.io/spring-boot/docs/3.0.4/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://unideal:changeme@db:3306/unideal

volumes:
  unideal-db_data:

# DO NOT REMOVE! - Mitigation for MTU 1400
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

