spring:
  application:
    name: unideal
  datasource:
    url: jdbc:mysql://localhost:3306/unideal
    username: unideal
    password: unideal
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    # Verbose logging for SQL
    show-sql: true

  jwt:
    token:
      secretKey: 6vOaMyJYfYpKzT0gYCw6FSFBsi9xA962
      expiration:
        access: 14400000


springdoc:
  api-docs:
    path: /openapi
