spring:
  application:
    name: unideal
  datasource:
    # TODO: Implement proper datasource
    url:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    # Verbose logging for SQL
    show-sql: true

springdoc:
  api-docs:
    path: /openapi
